<!DOCTYPE html>
<html>
<head lang="en">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <meta charset="UTF-8">
    <title>Message</title>
</head>
<body>

<header class="container">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mb_collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MessageBoard</a>
            </div>

            <div class="collapse navbar-collapse" id="mb_collapse">
                <ul class="nav navbar-nav">
                    <!--<li><a href="/new">New Message</a></li>-->
                </ul>
            </div>

        </div>
    </nav>
</header>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <form role="form" action="/new" method="post">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input class="form-control" id="title" type="text" name="title">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea id="message" class="form-control" rows="3" name="message"></textarea>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
</div>

<script src="../public/js/jquery.min.js"></script>
<script src="../public/js/html5shiv.js"></script>
<script src="../public/js/bootstrap.min.js"></script>

</body>
</html>