<!DOCTYPE html>
<html>
<head lang="en">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <meta charset="UTF-8">
    <title>Messages</title>
</head>
<body>

<header class="container">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mb_collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MessageBoard</a>
            </div>

            <div class="collapse navbar-collapse" id="mb_collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/new">New Message</a></li>
                </ul>
            </div>

        </div>
    </nav>
</header>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">

            <?php if (!empty($messages)) : ?>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Title</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($messages as $message) :?>
                <tr>
                    <td><?php echo $message['title']; ?></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php else : ?>
            <h4>No messages</h4>
            <?php endif; ?>

        </div>
    </div>
</div>

<script src="js/jquery.min.js"></script>
<script src="js/html5shiv.js"></script>
<script src="js/bootstrap.min.js"></script>

</body>
</html>